[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"
    Accept = "application/json"
    
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Content-Type = "application/json"
    Accept = "application/json"
